version: '3.4'

services:
  api:
    image: node:12.10.0-alpine
    volumes:
      - .:/api
    working_dir: /api
    command: sh -c 'npm i && npm run dev'
    env_file: .env
    ports:
      - 8000:8000

      